version: '3'

services:
  web:
    image: php:7.4-apache
    container_name: php_web
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - lamp

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: your_user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - lamp

networks:
  lamp:

volumes:
  db_data:
