apiVersion: v1
kind: Service
metadata:
  name: my-web-app-nodeport
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080
  type: NodePort

