apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels: 
    type: web
    paradigm: Devops
spec:
  containers:
    - name: nginxpod
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 80
