apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod
  labels:
    type: web
spec:
  containers:
    - name: tomcatpod
      image: tomcat
      ports:
        - containerPort: 8080
          hostPort: 8080
