apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-rolebinding
  namespace: prod-ns
subjects:
- kind: User
  name: prod-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-role
  apiGroup: rbac.authorization.k8s.io

