apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-st
spec:
  serviceName: mysql-st
  replicas: 3
  selector:
    matchLabels:
      app: mysql-st
  template:
    metadata:
      labels:
        app: mysql-st
    spec:
      containers:
      - name: mysql-st
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: levis-terence
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql-st
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
