apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-green
  template:
    metadata:
      labels:
        app: tomcat-green
    spec:
      containers:
      - name: tomcat
        image: tomcat:10.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

