apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: dev-ns
spec:
  containers:
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 8080
          hostPort: 9990
      volumeMounts:
        - name: webapps
          mountPath: /usr/local/tomcat/webapps
  volumes:
    - name: webapps
      emptyDir: {}
