apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rs
  labels:
    type: appserver
    author: paradigm
spec:
  replicas: 10
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: mytomcat
          image: tomcat:9.0
          ports:
            - containerPort: 8080
              hostPort: 8888
          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "50Mi"
